services:
  - type: static
    name: baosa-07
    repo: https://github.com/ayitteyg/baosa07-frontend.git
    branch: main
    buildCommand: npm install && npm run build --configuration production
    publishDir: dist/frontend
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
