services:
  - type: static
    name: my-angular-app
    repo: https://github.com/your-username/your-angular-repo
    branch: main
    buildCommand: npm install && npm run build --configuration production
    publishDir: dist/frontend
    redirects:
      - source: /*
        destination: /index.html
        statusCode: 200
